labaratore_last/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import register_view
app_name = 'accounts'

urlpatterns = [
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('accounts/reg/', register_view, name='registration')
]

labaratore_last/api_v1/urls.py
from django.urls import include, path
from rest_framework import routers
from api_v1 import views
from rest_framework.authtoken.views import obtain_auth_token
from api_v1.views import RatingAdd, RatingDelete


router = routers.DefaultRouter()
router.register('quote', views.QuoteAPI)

app_name = 'api_v1'


urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('login/', obtain_auth_token, name='api_token_auth'),
    path('rating_add/<int:pk>', RatingAdd.as_view(), name='rating_add'),
    path('rating_delete<int:pk>', RatingDelete.as_view(), name='rating_delete')
]

labaratore_last/labaratore_last/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

HOMEPAGE_URL = 'quote_home/'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('quote_home/', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/v1/', include('api_v1.urls')),
    path('', RedirectView.as_view(url=HOMEPAGE_URL, permanent=False))
]

labaratore_last/webapp/urls.py
from django.urls import path
from webapp.views import index

app_name = 'webapp'


urlpatterns = [
    path('', index, name='index' ),
]

labaratore_last/accounts/models.py
from django.db import models

# Create your models here.

labaratore_last/api_v1/models.py
from django.db import models

# Create your models here.

labaratore_last/webapp/models.py
from django.db import models
# Create your models here.
choices = [('new', 'New'), ('moder', 'Moder')]
from django.contrib.auth import get_user_model

class QuoteRating(models.Model):
    user = models.ForeignKey(get_user_model(), related_name='user', on_delete=models.CASCADE, verbose_name='Пользователь')
    quote = models.ForeignKey('webapp.Quote', on_delete=models.CASCADE, related_name='quote', verbose_name='Цитата')

class Quote(models.Model):
    text = models.CharField(max_length=3000, null=False, blank=False)
    name = models.CharField(max_length=300, null=False, blank=False)
    email = models.EmailField(null=False, blank=False)
    rating = models.ManyToManyField(get_user_model(), related_name='rating', through='webapp.QuoteRating' )
    status = models.CharField(max_length=300, null=False, blank=False, choices=choices, default='new')
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'Quote'
        verbose_name = 'Цитата'
        verbose_name_plural = 'Цитаты'

    def __str__(self):
        return f"{self.name} - {self.date} : {self.rating}"

labaratore_last/accounts/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth import get_user_model



class MyUserCreationForm(forms.ModelForm):
    password = forms.CharField(label="Пароль", strip=False, required=True, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Подтвердите пароль", required=True, widget=forms.PasswordInput, strip=False)
    email = forms.CharField(label='Email', required=True)

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_confirm = cleaned_data.get("password_confirm")
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        if not first_name and not last_name:
            raise forms.ValidationError('Заполните хотябы одно из полей FirstName, LastName')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['username', 'password', 'password_confirm', 'first_name', 'last_name', 'email']

labaratore_last/accounts/views.py
from django.shortcuts import render
from accounts.forms import MyUserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.

def register_view(request, *args, **kwargs):
    if request.method == 'POST':
        form = MyUserCreationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            user.save()
            return redirect('webapp:index')
    else:
        form = MyUserCreationForm()
    return render(request, 'register_user.html', context={'form': form})

labaratore_last/api_v1/views/quote.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.db.models import Q
from django.utils.http import urlencode
from rest_framework import generics
from api_v1.serializers import QuoteSerializer
from webapp.models import Quote
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated, IsAdminUser, AllowAny, BasePermission


class IsOwnerOrReadOnly(BasePermission):
    def has_permission(self, request, view):
        print(request.method)
        if view.action == 'partial_update' or view.action == 'destroy':
            return request.user.is_authenticated and request.user.is_superuser
        else :
            return True
        return True

    def has_object_permission(self, request, view, obj):
        if view.action == 'retrieve':
            if obj.status != 'moder':
                return request.user.is_authenticated and request.user.is_superuser
            else:
                return True
        return True



class QuoteAPI(viewsets.ModelViewSet):
    queryset = Quote.objects.all()
    serializer_class = QuoteSerializer
    permission_classes = (IsOwnerOrReadOnly,)


    def get_queryset(self):
        if not self.request.user.is_superuser:
            return Quote.objects.filter(status='moder')
        else:
            return Quote.objects.all()

labaratore_last/api_v1/views/rate.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.db.models import Q
from django.utils.http import urlencode
from rest_framework import generics
from api_v1.serializers import QuoteSerializer
from webapp.models import Quote
from rest_framework import viewsets
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    UpdateView,
    DeleteView,
    View
)
from rest_framework.permissions import IsAuthenticated, IsAdminUser, AllowAny, BasePermission

class RatingAdd(View):
    def get(self, request, *args, **kwargs):
        quote = get_object_or_404(Quote, pk=kwargs.get('pk'))
        user = self.request.user
        if user in quote.rating.all():
            raise ValueError("Рейтинг Уже был поставлен")
        else :
            quote.rating.add(user)
            quote.save()
        return JsonResponse({"data": "www"})


class RatingDelete(View):
    def get(self, request, *args, **kwargs):
        quote = get_object_or_404(Quote, pk=kwargs.get('pk'))
        user = self.request.user
        quote.rating.remove(user)
        quote.save()
        return JsonResponse({"data": "www"})

labaratore_last/webapp/views.py
from django.shortcuts import render
from django.views.generic import View
from django.views.decorators.csrf import ensure_csrf_cookie

# Create your views here.
@ensure_csrf_cookie
def index(request, *args, **kwargs):
    return render(request, 'index.html')

labaratore_last/accounts/templates/register_user.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

    <h1>Регистрация</h1>
<form action="{% url 'accounts:registration' %}" method="post">
     {% include 'partial/form.html' with button_text="Зарегистрироваться" %}
</form>


</body>
</html>

labaratore_last/webapp/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
</head>
<body>

<nav class="navbar navbar-expand-lg style='background-color: #e3f2fd;' navbar-light bg-light">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'webapp:index' %}">Home</a>
        </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
              <a href="{% url 'accounts:logout' %}?next={{ request.get_full_path }}" class="nav-link active" aria-current="page">Выход</a>
          </li>
          <li class="menu-right">Привет, <a href="#">{{ user.username }}</a>!</li>
       {% else %}
          <li class="nav-item">
              <a href="{% url 'accounts:login' %}?next={{ request.get_full_path }}" class="nav-link active" aria-current="page">Вход</a>
          </li>
          <li class="nav-item"><a href="{% url 'accounts:registration' %}?next={{ request.get_full_path }}" class="nav-link active" aria-current="page"">Регистрация</a>
          </li>
          {% endif %}
        {% block menu %}{% endblock %}
      </ul>
    </div>
  </div>
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
</body>
</html>

labaratore_last/webapp/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="list">
       <br>
    </div>
</div>

</div>

<script>
     function getCookie(name) {
  if (!document.cookie) {
    return null;
  }
  const xsrfCookies = document.cookie.split(';')
    .map(c => c.trim())
    .filter(c => c.startsWith(name + '='));

  if (xsrfCookies.length === 0) {
    return null;
  }
  return decodeURIComponent(xsrfCookies[0].split('=')[1]);
}

    async function List() {
        let response = fetch('http://localhost:8000/api/v1/quote/')
    response.then(function(response) { return response.json(); })
    .then(function(json) {
        const parce1 = json
        let container = document.getElementsByClassName('list')
        for (let i of parce1){
        let div = document.createElement('div')
        let div2 = document.createElement('div')
        div.classList.add('card')
        div.classList.add('text-center')
        div.style.width = '30rem'
        div2.classList.add('card-body')
        let h = document.createElement('h5')
        let h2 = document.createElement('h6')
        let p = document.createElement('p')
        let button = document.createElement('button')
        let button2 = document.createElement('button')
        let button3 = document.createElement('button')
        button.dataset.id = `${i.id}`
        button2.dataset.id = `${i.id}`
        button3.dataset.id = `${i.id}`
        button.onclick = Edit
        button2.onclick = View
        button3.onclick = Delete
        button.classList.add('btn')
        button.classList.add('btn-primary')
        button2.classList.add('btn')
        button2.classList.add('btn-primary')
        button3.classList.add('btn')
        button3.classList.add('btn-primary')
        let text = document.createTextNode(`${i.name}`)
        let text2 = document.createTextNode(`${i.text}`)
        let text3 = document.createTextNode(`${i.email}`)
        let text_button = document.createTextNode('Edit')
        let text_button2 = document.createTextNode('View')
        let text_button3 = document.createTextNode('Delete')
        button.appendChild(text_button)
        button2.appendChild(text_button2)
        button3.appendChild(text_button3)
        p.classList.add('card-text')
        p.appendChild(text3)
        h2.classList.add('card-subtitle')
        h2.classList.add('mb-2')
        h2.classList.add('text-muted')
        h2.appendChild(text2)
        h.classList.add('card-title')
        h.appendChild(text)
        div2.appendChild(h)
        div2.appendChild(h2)
        div2.appendChild(p)
        div2.appendChild(button)
        div2.appendChild(button2)
        div2.appendChild(button3)
        div.appendChild(div2)
        container[0].appendChild(div)
    }
    })
    }


    async function View(event) {
        let button = event.target
        event.preventDefault()
        let response = fetch(`http://localhost:8000/api/v1/quote/${button.dataset.id}/`)
        console.log(response);
        let div1 = document.getElementsByClassName('list')
        div1[0].style.opacity = '0'
        let div_container = document.getElementsByClassName('container')
        response.then(function(response) { return response.json(); })
        .then(function(json) {
            const parce1 = json
                let h = document.createElement('h4')
                let text = document.createTextNode(`${parce1.name}`)
                h.appendChild(text)
                div_container[0].appendChild(h)
                let h2 = document.createElement('h6')
                let text2 = document.createTextNode(`${parce1.text}`)
                h2.appendChild(text2)
                div_container[0].appendChild(h2)
                let p = document.createElement('p')
                let text3 = document.createTextNode(`${parce1.email}`)
                p.appendChild(text3)
                div_container[0].appendChild(p)
        })

    }

    async function Delete(event) {
        let button = event.target
        event.preventDefault()
        const csrfToken = getCookie('csrftoken')
        console.log(csrfToken);
        const headers = new Headers({
        'Content-Type': 'x-www-form-urlencoded',
         'X-CSRFToken' : csrfToken
         });
        let response = fetch(`http://localhost:8000/api/v1/quote/${button.dataset.id}/`, {
        method: 'DELETE',
        headers
        })
        .then(res => res.text())
        .then(res => console.log(res))

    }


    async function Edit(event) {
        let button_tar = event.target
        event.preventDefault()
        let div1 = document.getElementsByClassName('list')
        div1[0].style.opacity = '0'
        let container = document.getElementsByClassName('container')
        let a = document.createElement('input')
        let c = document.createElement('h4')
        let op = document.createElement('h3')
        let b = document.createElement('input')
        let c2 = document.createElement('input')
        let form = document.createElement('form')
        let text_h4 = document.createTextNode('Статус:')
        let text_h5 = document.createTextNode('Name:')
        c.appendChild(text_h4)
        op.appendChild(text_h5)
        let br = document.createElement('br')
        a.id = 'name'
        b.classList.add('radio')
        c2.classList.add('radio')
        b.type = 'checkbox'
        c2.type = 'checkbox'
        b.value = 'new'
        c2.value = 'moder'
        form.appendChild(b)
        form.appendChild(c2)
        let button = document.createElement('button')
        let text3 = document.createTextNode('Edit')
        button.appendChild(text3)
        button.dataset.id = button_tar.dataset.id
        button.onclick = EditOper
        container[0].appendChild(op)
        container[0].appendChild(a)
        container[0].appendChild(br)
        container[0].appendChild(c)
        container[0].appendChild(br)
        container[0].appendChild(form)
        container[0].appendChild(button)
    }

     async function EditOper(event) {
         let button = event.target
         event.preventDefault()
         let a = document.getElementById('name').value
         let b = document.getElementById('modercheck').value
         const csrfToken = getCookie('csrftoken')
        console.log(csrfToken);
        const headers = new Headers({
        'Content-Type': 'x-www-form-urlencoded',
         'X-CSRFToken' : csrfToken
         });
         fetch(`http://localhost:8000/api/v1/quote/,${button.dataset.id}`,{
             method: 'POST',
             headers,
             body: JSON.stringify({'name':  a, 'status' : b})
         })
         await List()

     }

     List()


</script>

{% endblock %}

labaratore_last/webapp/templates/partial/form.html
{% csrf_token %}
{% for error in form.non_field_errors %}
   <p class="form-error">{{ error }}</p>
{% endfor %}


{% for field in form %}
   <p><label for="{{ field.id_for_label }}">{{ field.label }}</label></p>
   {% for error in field.errors %}
       <p class="form-error">{{ error }}</p>
   {% endfor %}
   <p>{{ field }}</p>
{% endfor %}
<p><input type="submit" value="{{ button_text }}"></p>